name: mail
description: A simple mail interfaces package
version: 0.1.0
author: Long Do <me@dotronglong.com>
homepage: https://github.com/dotronglong/flutter-mail

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: